name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: create envfile
      run: |
       echo "export const environment = {
        production: true,
        apiUrl: 'http://APP_API_URL',
        tokenWhitelistedDomains: [new RegExp('APP_API_URL')],
        tokenBlacklistedRoutes: [new RegExp('/oauth/token')],
        };" > ./src/environments/environment.prod.ts
        
    - name: show env
      run: cat ./src/environments/environment.prod.ts
