name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout git files
      uses: actions/checkout@v3
    
    - name: create envfile
      run: |
       echo "export const environment = {
        production: true,
        apiUrl: 'http://APP_API_URL',
        tokenWhitelistedDomains: [new RegExp('APP_API_URL')],
        tokenBlacklistedRoutes: [new RegExp('/oauth/token')],
        };" > ./src/environments/environment.prod.t
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
       
    - name: docker build
      run: docker build . -f Dockerfile -tag ${{secrets.DOCKERHUB_USERNAME}}/sistemafui:${{steps.package-version.outputs.current-version}}
    
