name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout git files
      uses: actions/checkout@v3
    
    - name: create envfile
      run: |
       echo "export const environment = {
        production: true,
        apiUrl: 'http://APP_API_URL',
        tokenWhitelistedDomains: [new RegExp('APP_API_URL')],
        tokenBlacklistedRoutes: [new RegExp('/oauth/token')],
        };" > ./src/environments/environment.prod.t
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
       
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/sistemafui:0.5.0
    
